### ISSUE TITLE
What is DebugSQLTestResult and PDBDebugResult

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/django-plugin#12]
What are the classes mentioned in subject and when/how are they used ?

**Comment by brymut** [comment]
I noticed that in django's DiscoverRunner, apart from the default Result class, there are [2 more classes](https://github.com/django/django/blob/71756bdfed5029bd14dce8cb3c5629efc4be55ac/django/test/runner.py#L619) that are used when testing is run using either the `--debug-sql` or `--pdb` flags for debugging/logging functionality. 

So I thought to that bring over to this package as well so that they don't lose access to those features.
