### ISSUE TITLE
startTestRun() not calling super()

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/django-plugin#25]
I guess it should, right ?

**Comment by brymut** [comment]
I guess so too, I got mixed up about when to inherit from unittest's method functionality since a number of unittest's TextTestResult methods don't have any implementation such as startTestRun(), stopTestRun(), and addSuccess. However, I ended up not being consistent myself since I ended up missing some such as stopTest() which does have some impl. I think we should just call super() on all of them for consistency, all add them in the PR.
